// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.29.0--rc2
// source: rpc/package.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CpRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CpRequest) Reset() {
	*x = CpRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_package_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CpRequest) ProtoMessage() {}

func (x *CpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_package_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CpRequest.ProtoReflect.Descriptor instead.
func (*CpRequest) Descriptor() ([]byte, []int) {
	return file_rpc_package_proto_rawDescGZIP(), []int{0}
}

type CpResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *CpResponse) Reset() {
	*x = CpResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_package_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CpResponse) ProtoMessage() {}

func (x *CpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_package_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CpResponse.ProtoReflect.Descriptor instead.
func (*CpResponse) Descriptor() ([]byte, []int) {
	return file_rpc_package_proto_rawDescGZIP(), []int{1}
}

func (x *CpResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type PullCodeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url      string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Branch   string `protobuf:"bytes,2,opt,name=branch,proto3" json:"branch,omitempty"`
	Account  string `protobuf:"bytes,3,opt,name=account,proto3" json:"account,omitempty"`
	Password string `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *PullCodeRequest) Reset() {
	*x = PullCodeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_package_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PullCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullCodeRequest) ProtoMessage() {}

func (x *PullCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_package_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullCodeRequest.ProtoReflect.Descriptor instead.
func (*PullCodeRequest) Descriptor() ([]byte, []int) {
	return file_rpc_package_proto_rawDescGZIP(), []int{2}
}

func (x *PullCodeRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *PullCodeRequest) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

func (x *PullCodeRequest) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *PullCodeRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type PullCodeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *PullCodeResponse) Reset() {
	*x = PullCodeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_package_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PullCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullCodeResponse) ProtoMessage() {}

func (x *PullCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_package_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullCodeResponse.ProtoReflect.Descriptor instead.
func (*PullCodeResponse) Descriptor() ([]byte, []int) {
	return file_rpc_package_proto_rawDescGZIP(), []int{3}
}

func (x *PullCodeResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_rpc_package_proto protoreflect.FileDescriptor

var file_rpc_package_proto_rawDesc = []byte{
	0x0a, 0x11, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x03, 0x72, 0x70, 0x63, 0x22, 0x0b, 0x0a, 0x09, 0x43, 0x70, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x1e, 0x0a, 0x0a, 0x43, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x71, 0x0a, 0x0f, 0x50, 0x75, 0x6c, 0x6c, 0x43, 0x6f, 0x64,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x62, 0x72,
	0x61, 0x6e, 0x63, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x62, 0x72, 0x61, 0x6e,
	0x63, 0x68, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x08,
	0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x24, 0x0a, 0x10, 0x50, 0x75, 0x6c, 0x6c,
	0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03,
	0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x32, 0x7a,
	0x0a, 0x0b, 0x43, 0x6f, 0x64, 0x65, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x12, 0x30, 0x0a,
	0x0b, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0e, 0x2e, 0x72,
	0x70, 0x63, 0x2e, 0x43, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0f, 0x2e, 0x72,
	0x70, 0x63, 0x2e, 0x43, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x39, 0x0a, 0x08, 0x50, 0x75, 0x6c, 0x6c, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x14, 0x2e, 0x72, 0x70,
	0x63, 0x2e, 0x50, 0x75, 0x6c, 0x6c, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x15, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x50, 0x75, 0x6c, 0x6c, 0x43, 0x6f, 0x64, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x06, 0x5a, 0x04, 0x2f, 0x72,
	0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpc_package_proto_rawDescOnce sync.Once
	file_rpc_package_proto_rawDescData = file_rpc_package_proto_rawDesc
)

func file_rpc_package_proto_rawDescGZIP() []byte {
	file_rpc_package_proto_rawDescOnce.Do(func() {
		file_rpc_package_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_package_proto_rawDescData)
	})
	return file_rpc_package_proto_rawDescData
}

var file_rpc_package_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_rpc_package_proto_goTypes = []interface{}{
	(*CpRequest)(nil),        // 0: rpc.CpRequest
	(*CpResponse)(nil),       // 1: rpc.CpResponse
	(*PullCodeRequest)(nil),  // 2: rpc.PullCodeRequest
	(*PullCodeResponse)(nil), // 3: rpc.PullCodeResponse
}
var file_rpc_package_proto_depIdxs = []int32{
	0, // 0: rpc.CodePackage.CheckStatus:input_type -> rpc.CpRequest
	2, // 1: rpc.CodePackage.PullCode:input_type -> rpc.PullCodeRequest
	1, // 2: rpc.CodePackage.CheckStatus:output_type -> rpc.CpResponse
	3, // 3: rpc.CodePackage.PullCode:output_type -> rpc.PullCodeResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rpc_package_proto_init() }
func file_rpc_package_proto_init() {
	if File_rpc_package_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rpc_package_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CpRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_package_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CpResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_package_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PullCodeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_package_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PullCodeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_package_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_package_proto_goTypes,
		DependencyIndexes: file_rpc_package_proto_depIdxs,
		MessageInfos:      file_rpc_package_proto_msgTypes,
	}.Build()
	File_rpc_package_proto = out.File
	file_rpc_package_proto_rawDesc = nil
	file_rpc_package_proto_goTypes = nil
	file_rpc_package_proto_depIdxs = nil
}
