// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: rpc/package.proto

package rpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for CodePackage service

func NewCodePackageEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for CodePackage service

type CodePackageService interface {
	CheckStatus(ctx context.Context, in *CpRequest, opts ...client.CallOption) (*CpResponse, error)
}

type codePackageService struct {
	c    client.Client
	name string
}

func NewCodePackageService(name string, c client.Client) CodePackageService {
	return &codePackageService{
		c:    c,
		name: name,
	}
}

func (c *codePackageService) CheckStatus(ctx context.Context, in *CpRequest, opts ...client.CallOption) (*CpResponse, error) {
	req := c.c.NewRequest(c.name, "CodePackage.CheckStatus", in)
	out := new(CpResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for CodePackage service

type CodePackageHandler interface {
	CheckStatus(context.Context, *CpRequest, *CpResponse) error
}

func RegisterCodePackageHandler(s server.Server, hdlr CodePackageHandler, opts ...server.HandlerOption) error {
	type codePackage interface {
		CheckStatus(ctx context.Context, in *CpRequest, out *CpResponse) error
	}
	type CodePackage struct {
		codePackage
	}
	h := &codePackageHandler{hdlr}
	return s.Handle(s.NewHandler(&CodePackage{h}, opts...))
}

type codePackageHandler struct {
	CodePackageHandler
}

func (h *codePackageHandler) CheckStatus(ctx context.Context, in *CpRequest, out *CpResponse) error {
	return h.CodePackageHandler.CheckStatus(ctx, in, out)
}
