// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.4
// source: rpc/package.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CpRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CpRequest) Reset() {
	*x = CpRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_package_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CpRequest) ProtoMessage() {}

func (x *CpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_package_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CpRequest.ProtoReflect.Descriptor instead.
func (*CpRequest) Descriptor() ([]byte, []int) {
	return file_rpc_package_proto_rawDescGZIP(), []int{0}
}

type CpResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *CpResponse) Reset() {
	*x = CpResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_package_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CpResponse) ProtoMessage() {}

func (x *CpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_package_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CpResponse.ProtoReflect.Descriptor instead.
func (*CpResponse) Descriptor() ([]byte, []int) {
	return file_rpc_package_proto_rawDescGZIP(), []int{1}
}

func (x *CpResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type CloneCodesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *CloneCodesRequest) Reset() {
	*x = CloneCodesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_package_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CloneCodesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloneCodesRequest) ProtoMessage() {}

func (x *CloneCodesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_package_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloneCodesRequest.ProtoReflect.Descriptor instead.
func (*CloneCodesRequest) Descriptor() ([]byte, []int) {
	return file_rpc_package_proto_rawDescGZIP(), []int{2}
}

func (x *CloneCodesRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type CloneCodesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CloneCodesResponse) Reset() {
	*x = CloneCodesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_package_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CloneCodesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloneCodesResponse) ProtoMessage() {}

func (x *CloneCodesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_package_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloneCodesResponse.ProtoReflect.Descriptor instead.
func (*CloneCodesResponse) Descriptor() ([]byte, []int) {
	return file_rpc_package_proto_rawDescGZIP(), []int{3}
}

type StartPlanRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name       string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Url        string `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	IsFailPlan bool   `protobuf:"varint,3,opt,name=is_fail_plan,json=isFailPlan,proto3" json:"is_fail_plan,omitempty"`
	Id         int64  `protobuf:"varint,4,opt,name=id,proto3" json:"id,omitempty"`
	Version    string `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`
}

func (x *StartPlanRequest) Reset() {
	*x = StartPlanRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_package_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartPlanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartPlanRequest) ProtoMessage() {}

func (x *StartPlanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_package_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartPlanRequest.ProtoReflect.Descriptor instead.
func (*StartPlanRequest) Descriptor() ([]byte, []int) {
	return file_rpc_package_proto_rawDescGZIP(), []int{4}
}

func (x *StartPlanRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StartPlanRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *StartPlanRequest) GetIsFailPlan() bool {
	if x != nil {
		return x.IsFailPlan
	}
	return false
}

func (x *StartPlanRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *StartPlanRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type StartPlanResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name       string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Url        string `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	Status     int64  `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	Is_Success bool   `protobuf:"varint,5,opt,name=is_Success,json=isSuccess,proto3" json:"is_Success,omitempty"`
}

func (x *StartPlanResponse) Reset() {
	*x = StartPlanResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_package_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartPlanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartPlanResponse) ProtoMessage() {}

func (x *StartPlanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_package_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartPlanResponse.ProtoReflect.Descriptor instead.
func (*StartPlanResponse) Descriptor() ([]byte, []int) {
	return file_rpc_package_proto_rawDescGZIP(), []int{5}
}

func (x *StartPlanResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *StartPlanResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StartPlanResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *StartPlanResponse) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *StartPlanResponse) GetIs_Success() bool {
	if x != nil {
		return x.Is_Success
	}
	return false
}

type GetPlanStatusRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetPlanStatusRequest) Reset() {
	*x = GetPlanStatusRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_package_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPlanStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlanStatusRequest) ProtoMessage() {}

func (x *GetPlanStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_package_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlanStatusRequest.ProtoReflect.Descriptor instead.
func (*GetPlanStatusRequest) Descriptor() ([]byte, []int) {
	return file_rpc_package_proto_rawDescGZIP(), []int{6}
}

func (x *GetPlanStatusRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetPlanStatusResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name       string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Url        string `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	Status     int64  `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	Is_Success bool   `protobuf:"varint,5,opt,name=is_Success,json=isSuccess,proto3" json:"is_Success,omitempty"`
}

func (x *GetPlanStatusResponse) Reset() {
	*x = GetPlanStatusResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_package_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPlanStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlanStatusResponse) ProtoMessage() {}

func (x *GetPlanStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_package_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlanStatusResponse.ProtoReflect.Descriptor instead.
func (*GetPlanStatusResponse) Descriptor() ([]byte, []int) {
	return file_rpc_package_proto_rawDescGZIP(), []int{7}
}

func (x *GetPlanStatusResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetPlanStatusResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetPlanStatusResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *GetPlanStatusResponse) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GetPlanStatusResponse) GetIs_Success() bool {
	if x != nil {
		return x.Is_Success
	}
	return false
}

type ConfigureCIRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Repository    string   `protobuf:"bytes,1,opt,name=repository,proto3" json:"repository,omitempty"`
	Key           []string `protobuf:"bytes,2,rep,name=key,proto3" json:"key,omitempty"`
	Value         []string `protobuf:"bytes,3,rep,name=value,proto3" json:"value,omitempty"`
	Version       string   `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	Url           string   `protobuf:"bytes,5,opt,name=url,proto3" json:"url,omitempty"`
	Branch        string   `protobuf:"bytes,6,opt,name=branch,proto3" json:"branch,omitempty"`
	CommitMessage string   `protobuf:"bytes,7,opt,name=commit_message,json=commitMessage,proto3" json:"commit_message,omitempty"`
}

func (x *ConfigureCIRequest) Reset() {
	*x = ConfigureCIRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_package_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfigureCIRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureCIRequest) ProtoMessage() {}

func (x *ConfigureCIRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_package_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureCIRequest.ProtoReflect.Descriptor instead.
func (*ConfigureCIRequest) Descriptor() ([]byte, []int) {
	return file_rpc_package_proto_rawDescGZIP(), []int{8}
}

func (x *ConfigureCIRequest) GetRepository() string {
	if x != nil {
		return x.Repository
	}
	return ""
}

func (x *ConfigureCIRequest) GetKey() []string {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *ConfigureCIRequest) GetValue() []string {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *ConfigureCIRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ConfigureCIRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ConfigureCIRequest) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

func (x *ConfigureCIRequest) GetCommitMessage() string {
	if x != nil {
		return x.CommitMessage
	}
	return ""
}

type ConfigureCIResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg  string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *ConfigureCIResponse) Reset() {
	*x = ConfigureCIResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_package_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfigureCIResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureCIResponse) ProtoMessage() {}

func (x *ConfigureCIResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_package_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureCIResponse.ProtoReflect.Descriptor instead.
func (*ConfigureCIResponse) Descriptor() ([]byte, []int) {
	return file_rpc_package_proto_rawDescGZIP(), []int{9}
}

func (x *ConfigureCIResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ConfigureCIResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_rpc_package_proto protoreflect.FileDescriptor

var file_rpc_package_proto_rawDesc = []byte{
	0x0a, 0x11, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x03, 0x72, 0x70, 0x63, 0x22, 0x0b, 0x0a, 0x09, 0x43, 0x70, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x1e, 0x0a, 0x0a, 0x43, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x25, 0x0a, 0x11, 0x43, 0x6c, 0x6f, 0x6e, 0x65, 0x43, 0x6f,
	0x64, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72,
	0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x22, 0x14, 0x0a, 0x12,
	0x43, 0x6c, 0x6f, 0x6e, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x84, 0x01, 0x0a, 0x10, 0x53, 0x74, 0x61, 0x72, 0x74, 0x50, 0x6c, 0x61, 0x6e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x75,
	0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x20, 0x0a,
	0x0c, 0x69, 0x73, 0x5f, 0x66, 0x61, 0x69, 0x6c, 0x5f, 0x70, 0x6c, 0x61, 0x6e, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x0a, 0x69, 0x73, 0x46, 0x61, 0x69, 0x6c, 0x50, 0x6c, 0x61, 0x6e, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x80, 0x01, 0x0a, 0x11, 0x53, 0x74,
	0x61, 0x72, 0x74, 0x50, 0x6c, 0x61, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1d, 0x0a,
	0x0a, 0x69, 0x73, 0x5f, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x09, 0x69, 0x73, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x26, 0x0a, 0x14,
	0x47, 0x65, 0x74, 0x50, 0x6c, 0x61, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x02, 0x69, 0x64, 0x22, 0x84, 0x01, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x50, 0x6c, 0x61, 0x6e,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x75, 0x72, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1d, 0x0a, 0x0a,
	0x69, 0x73, 0x5f, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x09, 0x69, 0x73, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0xc7, 0x01, 0x0a, 0x12,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x65, 0x43, 0x49, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x72, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x72, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x6f,
	0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x62, 0x72, 0x61, 0x6e, 0x63, 0x68,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x62, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x12, 0x25,
	0x0a, 0x0e, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x3b, 0x0a, 0x13, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75,
	0x72, 0x65, 0x43, 0x49, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65,
	0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d,
	0x73, 0x67, 0x32, 0xcc, 0x02, 0x0a, 0x0b, 0x43, 0x6f, 0x64, 0x65, 0x50, 0x61, 0x63, 0x6b, 0x61,
	0x67, 0x65, 0x12, 0x30, 0x0a, 0x0b, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x0e, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x43, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x0f, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x43, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x3f, 0x0a, 0x0a, 0x43, 0x6c, 0x6f, 0x6e, 0x65, 0x43, 0x6f, 0x64,
	0x65, 0x73, 0x12, 0x16, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x43, 0x6c, 0x6f, 0x6e, 0x65, 0x43, 0x6f,
	0x64, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x72, 0x70, 0x63,
	0x2e, 0x43, 0x6c, 0x6f, 0x6e, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3c, 0x0a, 0x09, 0x53, 0x74, 0x61, 0x72, 0x74, 0x50, 0x6c,
	0x61, 0x6e, 0x12, 0x15, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x50, 0x6c,
	0x61, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x72, 0x70, 0x63, 0x2e,
	0x53, 0x74, 0x61, 0x72, 0x74, 0x50, 0x6c, 0x61, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x48, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x50, 0x6c, 0x61, 0x6e, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x19, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x6c,
	0x61, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1a, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x6c, 0x61, 0x6e, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x42, 0x0a,
	0x0b, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x65, 0x43, 0x49, 0x12, 0x17, 0x2e, 0x72,
	0x70, 0x63, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x65, 0x43, 0x49, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x75, 0x72, 0x65, 0x43, 0x49, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x42, 0x06, 0x5a, 0x04, 0x2f, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_rpc_package_proto_rawDescOnce sync.Once
	file_rpc_package_proto_rawDescData = file_rpc_package_proto_rawDesc
)

func file_rpc_package_proto_rawDescGZIP() []byte {
	file_rpc_package_proto_rawDescOnce.Do(func() {
		file_rpc_package_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_package_proto_rawDescData)
	})
	return file_rpc_package_proto_rawDescData
}

var file_rpc_package_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_rpc_package_proto_goTypes = []interface{}{
	(*CpRequest)(nil),             // 0: rpc.CpRequest
	(*CpResponse)(nil),            // 1: rpc.CpResponse
	(*CloneCodesRequest)(nil),     // 2: rpc.CloneCodesRequest
	(*CloneCodesResponse)(nil),    // 3: rpc.CloneCodesResponse
	(*StartPlanRequest)(nil),      // 4: rpc.StartPlanRequest
	(*StartPlanResponse)(nil),     // 5: rpc.StartPlanResponse
	(*GetPlanStatusRequest)(nil),  // 6: rpc.GetPlanStatusRequest
	(*GetPlanStatusResponse)(nil), // 7: rpc.GetPlanStatusResponse
	(*ConfigureCIRequest)(nil),    // 8: rpc.ConfigureCIRequest
	(*ConfigureCIResponse)(nil),   // 9: rpc.ConfigureCIResponse
}
var file_rpc_package_proto_depIdxs = []int32{
	0, // 0: rpc.CodePackage.CheckStatus:input_type -> rpc.CpRequest
	2, // 1: rpc.CodePackage.CloneCodes:input_type -> rpc.CloneCodesRequest
	4, // 2: rpc.CodePackage.StartPlan:input_type -> rpc.StartPlanRequest
	6, // 3: rpc.CodePackage.GetPlanStatus:input_type -> rpc.GetPlanStatusRequest
	8, // 4: rpc.CodePackage.ConfigureCI:input_type -> rpc.ConfigureCIRequest
	1, // 5: rpc.CodePackage.CheckStatus:output_type -> rpc.CpResponse
	3, // 6: rpc.CodePackage.CloneCodes:output_type -> rpc.CloneCodesResponse
	5, // 7: rpc.CodePackage.StartPlan:output_type -> rpc.StartPlanResponse
	7, // 8: rpc.CodePackage.GetPlanStatus:output_type -> rpc.GetPlanStatusResponse
	9, // 9: rpc.CodePackage.ConfigureCI:output_type -> rpc.ConfigureCIResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rpc_package_proto_init() }
func file_rpc_package_proto_init() {
	if File_rpc_package_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rpc_package_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CpRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_package_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CpResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_package_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CloneCodesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_package_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CloneCodesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_package_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartPlanRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_package_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartPlanResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_package_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPlanStatusRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_package_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPlanStatusResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_package_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConfigureCIRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_package_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConfigureCIResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_package_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_package_proto_goTypes,
		DependencyIndexes: file_rpc_package_proto_depIdxs,
		MessageInfos:      file_rpc_package_proto_msgTypes,
	}.Build()
	File_rpc_package_proto = out.File
	file_rpc_package_proto_rawDesc = nil
	file_rpc_package_proto_goTypes = nil
	file_rpc_package_proto_depIdxs = nil
}
